kind: Deployment # Specifies that this is a Deployment resource
apiVersion: apps/v1 # The API version being used
metadata:
  name: nginx-deployment # Name of the Deployment
  namespace: nginx # Namespace in which the Deployment is created
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: nginx # Label selector for pods
  template:
    metadata:
      name: nginx-dep-pod # Name of the pod template
      labels:
        app: nginx # Labels for the pod template
    spec:
      containers:
      - name: nginx # Name of the container
        image: nginx:latest # Docker image to use for the container
        ports:
        - containerPort: 80 # Port to expose on the container