kind: Deployment # Specifies the kind of Kubernetes object
apiVersion: apps/v1 # Specifies the API version
metadata:
  name: nginx-deployment # Name of the deployment
  namespace: nginx # Namespace where the deployment will be created
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: nginx # Label selector for pods
  template:
    metadata:
      name: nginx-dep-pod # Name of the pod template
      labels:
        app: nginx # Labels for the pod
    spec:
      containers:
      - name: nginx # Name of the container
        image: nginx:latest # Docker image to use for the container
        ports:
        - containerPort: 80 # Port to expose on the container
        resources:
          requests:
            cpu: 100m # CPU request for the container
            memory: 128Mi # Memory request for the container
          limits:
            cpu: 200m # CPU limit for the container
            memory: 256Mi # Memory limit for the container
        volumeMounts:
        - mountPath: /usr/share/nginx/html # Path to mount the volume inside the container
          name: my-volume # Name of the volume to mount
      volumes:
      - name: my-volume # Name of the volume
        persistentVolumeClaim:
          claimName: local-pvc # Name of the PersistentVolumeClaim