kind: Pod # Specifies the type of Kubernetes object
apiVersion: v1 # Specifies the API version
metadata:
  name: nginx-pod # Name of the Pod
  namespace: nginx # Namespace in which the Pod is created
spec:
  containers:
  - name: nginx # Name of the container
    image: nginx:latest # Docker image to use for the container
    ports: 
    - containerPort: 80 # Port to expose on the container
