kind: ReplicaSet # Specifies the kind of Kubernetes object
apiVersion: apps/v1 # Specifies the API version
metadata:
  name: nginx-repliacset # Name of the ReplicaSet
  namespace: nginx # Namespace in which the ReplicaSet is created
spec:
  replicas: 2 # Number of desired pod replicas
  selector:
    matchLabels:
      app: nginx # Label selector for pods
  template:
    metadata:
      name: nginx-rep-pod # Name of the pod template
      labels:
        app: nginx # Labels for the pod template
    spec:
      containers:
      - name: nginx # Name of the container
        image: nginx:latest # Docker image to use for the container
        ports:
        - containerPort: 80 # Port to expose on the container
