kind: Service # Specifies the type of Kubernetes object
apiVersion: v1 # Specifies the API version
metadata: # Metadata about the object
  name: nginx-service # Name of the service
  namespace: nginx # Namespace in which the service is created
spec: # Specification of the service
  selector: # Selector to identify the pods that the service targets
    app: nginx # Label selector to match the pods with label app: nginx
  ports: # List of ports that the service exposes
    - protocol: TCP # Protocol used by the service
      port: 80 # Port on which the service is exposed
      targetPort: 80 # Port on the pod to which the traffic is forwarded
  type: ClusterIP # Type of the service (ClusterIP, NodePort, LoadBalancer, etc.)