kind: Service # Specifies the type of Kubernetes object
apiVersion: v1 # API version used to create the object
metadata:
  name: nginx-service # Name of the service
  namespace: nginx # Namespace in which the service is created
spec:
  selector:
    app: nginx # Label selector to identify the pods
  ports:
    - protocol: TCP # Protocol used by the service
      port: 80 # Port exposed by the service
      targetPort: 80 # Port on the container to which the traffic is forwarded
  type: ClusterIP # Type of service (ClusterIP, NodePort, LoadBalancer, etc.)